Post http://localhost:3002/usuarios
content-type: application/json

{"email":"f@g.com","password":"123456"}


###
GET  http://localhost:3002/news




###
GET http://localhost:3001/getdatos?zona=General%20Paz

###
POST http://localhost:3001/reset-password
content-type: application/json

   {"token": "vyyy4g", "password": "1234567" }
###
Post https://newsbackprisma.vercel.app//nuevousuario
content-type: application/json

{"email":"mresnicoff@gmail.com","nombre":"martin resnicoff", "avatar":"no tiene","passhasheada":"Hola Chicos como les va", "puedeescribir":"false",}