Post http://localhost:3002/usuarios
content-type: application/json

{"email":"f@g.com","password":"123456"}


###
POST https://newsbackprisma.vercel.app/registrarse
content-type: application/json

{"email":"f@g.com","password":"123456"}

###
GET http://localhost:3001/getdatos?zona=General%20Paz

###
POST http://localhost:3001/reset-password
content-type: application/json

   {"token": "vyyy4g", "password": "1234567" }
###
Post http://localhost:3001/upload
content-type: application/json

{"name":"RMC","email":"mresnicoff@gmail.com", "subject":"mentorias","message":"Hola Chicos como les va"}
